### PR TITLE
openSSL Certificate Revocation List (CRL) implementation

### PR DESCRIPTION
**Pull request by rokonrad**
Hi Gaulthier,

here is my announced pull-request :-)

openSSL Certificate Revocation List (CRL) implementation incl. new option  MHD_OPTION_TLS_CLIENT_CERTIFICATE_MODE

Greets
Roman

### CODE REVIEW

**Comment by ghaderer** [comment]
Hello. Sorry for not reviewing your changes earlier. I postponed the review a few times as I was busy and finally forgot about it!

Your changes look good. Could you just rework your history to suppress merge commits and squash commits appropriately?

**Comment by rokonrad** [comment]
Hi, sounds good. Unfortunately I didn't figure out how to rework the history appropriately.
I tried
`git rebase -i --preserve-merges HEAD~7`
and used 'f' for the merge commits to fix them up. That screwed everything up and I had to use
`git reflog`
to get back.
Do you know how to do it appropriately?

**Comment by ghaderer** [comment]
I used this procecude on my side and it seems to solve the merge commit mess. I'm assuming the remote `ghaderer` points to my repository.

```
git fetch ghaderer
git rebase -i ghaderer/wip-openssl-master
-> don't pick the first 3 commits (4785fd97, 7704b8b1 and 31c25f6d) as the're duplicates of commits 4 to 6
-> then let rebase proceed
```

Now you should have a linear history of your commits.

**Comment by rokonrad** [comment]
Yes that did the trick, thank's a lot!

**Comment by ghaderer** [comment]
Great! Let me know when your rework of the history is done.

**Comment by rokonrad** [comment]
I'v done the rework of the history yesterday, so it's done :-)
Nevertheless one last merge commit entry seems to be necessary.

**Comment by ghaderer** [comment]
Hmm, I may have missed something but your history still contains many branches and merge commits. I would expect to have a linear history on top of the last commit of branch wip-openssl-master.

**Comment by rokonrad** [comment]
Hmmm I've done it exactly as you supposed. My forked repository has exactly 2 branches like yours, master and wip-openssl-master, where the latter one includes my changes and has been selected for the pull request.
So what do you suppose to fix that?

**Comment by ghaderer** [comment]
Great! Your history is linear now. But could you squash them properly to avoid "wording" or "fixes" commits?

As a suggestion, I would create two commits, one for each option you added. What do you think?

**Comment by rokonrad** [comment]
Wow, if one knows how to do it then it's not a big deal. But if not...

DONE!

**Comment by ghaderer** [comment]
Thanks!

**Pull request merged**
